"""initial full tables

Revision ID: 4ad90aebab4c
Revises:
Create Date: 2026-07-29 14:16:33.517701

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4ad90aebab4c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("COMPLETED", "REJECTED", name="receipt_record_result_enum").create(op.get_bind())
    sa.Enum(
        "ACCEPTED",
        "SERVICE_UNAVAILABLE",
        "NETWORK_ERROR",
        "TIMEOUT",
        "UNEXPECTED_ERROR",
        name="provider_attempt_outcome_enum",
    ).create(op.get_bind())
    sa.Enum("SUBMIT", "RETRY", "RECOVERY", name="provider_attempt_triggered_by_enum").create(op.get_bind())
    sa.Enum("CREATED", "PROCESSING", "COMPLETED", "REJECTED", name="operation_event_to_status_enum").create(
        op.get_bind()
    )
    sa.Enum("CREATED", "PROCESSING", "COMPLETED", "REJECTED", name="operation_event_from_status_enum").create(
        op.get_bind()
    )
    sa.Enum(
        "CREATED",
        "SUBMIT_ACCEPTED",
        "SUBMIT_DUPLICATE_IGNORED",
        "PROVIDER_CALL_ATTEMPTED",
        "PROVIDER_PAYMENT_ID_ASSIGNED",
        "PROVIDER_CALL_FAILED",
        "PROVIDER_LATE_RESPONSE_IGNORED",
        "RECOVERY_RESUMED",
        "RECEIPT_APPLIED",
        "RECEIPT_DUPLICATE_IGNORED",
        "RECEIPT_CONFLICT_IGNORED",
        "RECEIPT_PAYMENT_ID_MISMATCH",
        name="operation_event_type_enum",
    ).create(op.get_bind())
    sa.Enum("CREATED", "PROCESSING", "COMPLETED", "REJECTED", name="operation_status_enum").create(op.get_bind())
    sa.Enum("RUB", name="operation_currency_enum").create(op.get_bind())
    op.create_table(
        "operation",
        sa.Column("operationId", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column(
            "currency", postgresql.ENUM("RUB", name="operation_currency_enum", create_type=False), nullable=False
        ),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "CREATED", "PROCESSING", "COMPLETED", "REJECTED", name="operation_status_enum", create_type=False
            ),
            server_default="CREATED",
            nullable=False,
        ),
        sa.Column("providerPaymentId", sa.UUID(), nullable=True),
        sa.Column("createdAt", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("operationId"),
        sa.UniqueConstraint("providerPaymentId"),
    )
    op.create_table(
        "operation_event",
        sa.Column("eventId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operationId", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "CREATED",
                "SUBMIT_ACCEPTED",
                "SUBMIT_DUPLICATE_IGNORED",
                "PROVIDER_CALL_ATTEMPTED",
                "PROVIDER_PAYMENT_ID_ASSIGNED",
                "PROVIDER_CALL_FAILED",
                "PROVIDER_LATE_RESPONSE_IGNORED",
                "RECOVERY_RESUMED",
                "RECEIPT_APPLIED",
                "RECEIPT_DUPLICATE_IGNORED",
                "RECEIPT_CONFLICT_IGNORED",
                "RECEIPT_PAYMENT_ID_MISMATCH",
                name="operation_event_type_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "fromStatus",
            postgresql.ENUM(
                "CREATED",
                "PROCESSING",
                "COMPLETED",
                "REJECTED",
                name="operation_event_from_status_enum",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "toStatus",
            postgresql.ENUM(
                "CREATED",
                "PROCESSING",
                "COMPLETED",
                "REJECTED",
                name="operation_event_to_status_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("occurredAt", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["operationId"], ["operation.operationId"], name="operation_event_operation_id_fk", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("eventId"),
    )
    op.create_index(op.f("ix_operation_event_operationId"), "operation_event", ["operationId"], unique=False)
    op.create_table(
        "provider_attempt",
        sa.Column("providerAttemptId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operationId", sa.String(length=255), nullable=False),
        sa.Column("attemptNumber", sa.Integer(), nullable=False),
        sa.Column("requestedAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "triggeredBy",
            postgresql.ENUM(
                "SUBMIT", "RETRY", "RECOVERY", name="provider_attempt_triggered_by_enum", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            postgresql.ENUM(
                "ACCEPTED",
                "SERVICE_UNAVAILABLE",
                "NETWORK_ERROR",
                "TIMEOUT",
                "UNEXPECTED_ERROR",
                name="provider_attempt_outcome_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("httpStatusCode", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["operationId"], ["operation.operationId"], name="provider_attempt_operation_id_fk", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("providerAttemptId"),
    )
    op.create_index(op.f("ix_provider_attempt_operationId"), "provider_attempt", ["operationId"], unique=False)
    op.create_table(
        "receipt_record",
        sa.Column("receiptRecordId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operationId", sa.String(length=255), nullable=False),
        sa.Column("providerPaymentId", sa.UUID(), nullable=False),
        sa.Column(
            "result",
            postgresql.ENUM("COMPLETED", "REJECTED", name="receipt_record_result_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("providerMessage", sa.Text(), nullable=True),
        sa.Column("occurredAtProvider", sa.DateTime(timezone=True), nullable=False),
        sa.Column("receivedAt", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("eventId", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["eventId"], ["operation_event.eventId"], name="receipt_record_event_id_fk", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["operationId"], ["operation.operationId"], name="receipt_record_operation_id_fk", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("receiptRecordId"),
        sa.UniqueConstraint("eventId"),
    )
    op.create_index(op.f("ix_receipt_record_operationId"), "receipt_record", ["operationId"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_receipt_record_operationId"), table_name="receipt_record")
    op.drop_table("receipt_record")
    op.drop_index(op.f("ix_provider_attempt_operationId"), table_name="provider_attempt")
    op.drop_table("provider_attempt")
    op.drop_index(op.f("ix_operation_event_operationId"), table_name="operation_event")
    op.drop_table("operation_event")
    op.drop_table("operation")
    sa.Enum("RUB", name="operation_currency_enum").drop(op.get_bind())
    sa.Enum("CREATED", "PROCESSING", "COMPLETED", "REJECTED", name="operation_status_enum").drop(op.get_bind())
    sa.Enum(
        "CREATED",
        "SUBMIT_ACCEPTED",
        "SUBMIT_DUPLICATE_IGNORED",
        "PROVIDER_CALL_ATTEMPTED",
        "PROVIDER_PAYMENT_ID_ASSIGNED",
        "PROVIDER_CALL_FAILED",
        "PROVIDER_LATE_RESPONSE_IGNORED",
        "RECOVERY_RESUMED",
        "RECEIPT_APPLIED",
        "RECEIPT_DUPLICATE_IGNORED",
        "RECEIPT_CONFLICT_IGNORED",
        "RECEIPT_PAYMENT_ID_MISMATCH",
        name="operation_event_type_enum",
    ).drop(op.get_bind())
    sa.Enum("CREATED", "PROCESSING", "COMPLETED", "REJECTED", name="operation_event_from_status_enum").drop(
        op.get_bind()
    )
    sa.Enum("CREATED", "PROCESSING", "COMPLETED", "REJECTED", name="operation_event_to_status_enum").drop(
        op.get_bind()
    )
    sa.Enum("SUBMIT", "RETRY", "RECOVERY", name="provider_attempt_triggered_by_enum").drop(op.get_bind())
    sa.Enum(
        "ACCEPTED",
        "SERVICE_UNAVAILABLE",
        "NETWORK_ERROR",
        "TIMEOUT",
        "UNEXPECTED_ERROR",
        name="provider_attempt_outcome_enum",
    ).drop(op.get_bind())
    sa.Enum("COMPLETED", "REJECTED", name="receipt_record_result_enum").drop(op.get_bind())
    # ### end Alembic commands ###
