"""receipt vars renames

Revision ID: 486b82cd8234
Revises: 4ad90aebab4c
Create Date: 2026-07-29 20:26:56.720178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "486b82cd8234"
down_revision: Union[str, Sequence[str], None] = "4ad90aebab4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("receipt_record", sa.Column("message", sa.Text(), nullable=True))
    op.add_column("receipt_record", sa.Column("occurredAt", sa.DateTime(timezone=True), nullable=False))
    op.drop_column("receipt_record", "occurredAtProvider")
    op.drop_column("receipt_record", "providerMessage")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("receipt_record", sa.Column("providerMessage", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "receipt_record",
        sa.Column("occurredAtProvider", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.drop_column("receipt_record", "occurredAt")
    op.drop_column("receipt_record", "message")
    # ### end Alembic commands ###
